<?php

$charsetEncodings = array(  'Big5',
                            'EUC-JP',
                            'EUC-KR',
                            'GB2312',
                            'ISO-2022-JP',
                            'ISO-8859-1',
                            'ISO-8859-10',
                            'ISO-8859-13',
                            'ISO-8859-14',
                            'ISO-8859-15',
                            'ISO-8859-2',
                            'ISO-8859-3',
                            'ISO-8859-4',
                            'ISO-8859-5',
                            'ISO-8859-6',
                            'ISO-8859-6-e',
                            'ISO-8859-6-i',
                            'ISO-8859-7',
                            'ISO-8859-8',
                            'ISO-8859-8-e',
                            'ISO-8859-8-i',
                            'ISO-8859-9',
                            'KOI8-R',
                            'KOI8-U',
                            'Shift_JIS',
                            'TCVN-5712',
                            'TIS-620',
                            'UTF-16',
                            'UTF-16BE',
                            'UTF-16LE',
                            'UTF-8',
                            'VISCII',
                            'VPS',
                            'cp866',
                            'cp874',
                            'windows-1250',
                            'windows-1251',
                            'windows-1252',
                            'windows-1253',
                            'windows-1254',
                            'windows-1255',
                            'windows-1256',
                            'windows-1257',
                            'windows-1258'  );

?>