<?php

$ISO_639_1_LanguageCodes = array(  array(  "Afar",                           'aa'),
                                  array(  "Abkhazian",                      'ab'),
                                  array(  "Afrikaans",                      'af'),
                                  array(  "Amharic",                        'am'),
                                  array(  "Arabic",                         'ar'),
                                  array(  "Assamese",                       'as'),
                                  array(  "Aymara",                         'ay'),
                                  array(  "Azerbaijani",                    'az'),
                                  array(  "Bashkir",                        'ba'),
                                  array(  "Byelorussian (Belarusian)",      'be'),
                                  array(  "Bulgarian",                      'bg'),
                                  array(  "Bihari",                         'bh'),
                                  array(  "Bislama",                        'bi'),
                                  array(  "Bengali (Bangla)",               'bn'),
                                  array(  "Tibetan",                        'bo'),
                                  array(  "Breton",                         'br'),
                                  array(  "Catalan",                        'ca'),
                                  array(  "Corsican",                       'co'),
                                  array(  "Czech",                          'cs'),
                                  array(  "Welsh",                          'cy'),
                                  array(  "Danish",                         'da'),
                                  array(  "German",                         'de'),
                                  array(  "Divehi",                         'dv'),
                                  array(  "Bhutani",                        'dz'),
                                  array(  "Greek",                          'el'),
                                  array(  "English",                        'en'),
                                  array(  "Esperanto",                      'eo'),
                                  array(  "Spanish",                        'es'),
                                  array(  "Estonian",                       'et'),
                                  array(  "Basque",                         'eu'),
                                  array(  "Farsi",                          'fa'),
                                  array(  "Finnish",                        'fi'),
                                  array(  "Fiji",                           'fj'),
                                  array(  "Faeroese",                       'fo'),
                                  array(  "French",                         'fr'),
                                  array(  "Frisian",                        'fy'),
                                  array(  "Irish",                          'ga'),
                                  array(  "Gaelic (Scottish)",              'gd'),
                                  array(  "Galician",                       'gl'),
                                  array(  "Guarani",                        'gn'),
                                  array(  "Gujarati",                       'gu'),
                                  array(  "Gaelic (Manx)",                  'gv'),
                                  array(  "Hausa",                          'ha'),
                                  array(  "Hebrew",                         'he'),
                                  array(  "Hindi",                          'hi'),
                                  array(  "Croatian",                       'hr'),
                                  array(  "Hungarian",                      'hu'),
                                  array(  "Armenian",                       'hy'),
                                  array(  "Interlingua",                    'ia'),
                                  array(  "Indonesian",                     'id'),
                                  array(  "Interlingue",                    'ie'),
                                  array(  "Inupiak",                        'ik'),
                                  array(  "Icelandic",                      'is'),
                                  array(  "Italian",                        'it'),
                                  array(  "Inuktitut",                      'iu'),
                                  array(  "Japanese",                       'ja'),
                                  array(  "Javanese",                       'jv'),
                                  array(  "Georgian",                       'ka'),
                                  array(  "Kazakh",                         'kk'),
                                  array(  "Greenlandic",                    'kl'),
                                  array(  "Cambodian",                      'km'),
                                  array(  "Kannada",                        'kn'),
                                  array(  "Korean",                         'ko'),
                                  array(  "Kashmiri",                       'ks'),
                                  array(  "Kurdish",                        'ku'),
                                  array(  "Cornish",                         'kw'),
                                  array(  "Kirghiz",                        'ky'),
                                  array(  "Latin",                          'la'),
                                  array(  "Limburgish ( Limburger)",        'li'),
                                  array(  "Lingala",                        'ln'),
                                  array(  "Laothian",                       'lo'),
                                  array(  "Lithuanian",                     'lt'),
                                  array(  "Latvian (Lettish)",              'lv'),
                                  array(  "Malagasy",                       'mg'),
                                  array(  "Maori",                          'mi'),
                                  array(  "Macedonian",                     'mk'),
                                  array(  "Malayalam",                      'ml'),
                                  array(  "Mongolian",                      'mn'),
                                  array(  "Moldavian",                      'mo'),
                                  array(  "Marathi",                        'mr'),
                                  array(  "Malay",                          'ms'),
                                  array(  "Maltese",                        'mt'),
                                  array(  "Burmese",                        'my'),
                                  array(  "Nauru",                          'na'),
                                  array(  "Nepali",                         'ne'),
                                  array(  "Dutch",                          'nl'),
                                  array(  "Norwegian",                      'no'),
                                  array(  "Occitan",                        'oc'),
                                  array(  "Oromo (Afan, Galla)",            'om'),
                                  array(  "Oriya",                          'or'),
                                  array(  "Punjabi",                        'pa'),
                                  array(  "Polish",                         'pl'),
                                  array(  "Pashto (Pushto)",                'ps'),
                                  array(  "Portuguese",                     'pt'),
                                  array(  "Quechua",                        'qu'),
                                  array(  "Rhaeto-Romance",                 'rm'),
                                  array(  "Kirundi (Rundi)",                'rn'),
                                  array(  "Romanian",                       'ro'),
                                  array(  "Russian",                        'ru'),
                                  array(  "Kinyarwanda (Ruanda)",           'rw'),
                                  array(  "Sanskrit",                       'sa'),
                                  array(  "Sindhi",                         'sd'),
                                  array(  "Sangro",                         'sg'),
                                  array(  "Serbo-Croatian",                 'sh'),
                                  array(  "Sinhalese",                      'si'),
                                  array(  "Slovak",                         'sk'),
                                  array(  "Slovenian",                      'sl'),
                                  array(  "Samoan",                         'sm'),
                                  array(  "Shona",                          'sn'),
                                  array(  "Somali",                         'so'),
                                  array(  "Albanian",                       'sq'),
                                  array(  "Serbian",                        'sr'),
                                  array(  "Siswati",                        'ss'),
                                  array(  "Sesotho",                        'st'),
                                  array(  "Sundanese",                      'su'),
                                  array(  "Swedish",                        'sv'),
                                  array(  "Swahili (Kiswahili)",            'sw'),
                                  array(  "Tamil",                          'ta'),
                                  array(  "Telugu",                         'te'),
                                  array(  "Tajik",                          'tg'),
                                  array(  "Thai",                           'th'),
                                  array(  "Tigrinya",                       'ti'),
                                  array(  "Turkmen",                        'tk'),
                                  array(  "Tagalog",                        'tl'),
                                  array(  "Setswana",                       'tn'),
                                  array(  "Tonga",                          'to'),
                                  array(  "Turkish",                        'tr'),
                                  array(  "Tsonga",                         'ts'),
                                  array(  "Tatar",                          'tt'),
                                  array(  "Twi",                            'tw'),
                                  array(  "Uighur",                         'ug'),
                                  array(  "Ukrainian",                      'uk'),
                                  array(  "Urdu",                           'ur'),
                                  array(  "Uzbek",                          'uz'),
                                  array(  "Vietnamese",                     'vi'),
                                  array(  "Volapük",                        'vo'),
                                  array(  "Wolof",                          'wo'),
                                  array(  "Xhosa",                          'xh'),
                                  array(  "Yiddish",                        'yi'),
                                  array(  "Yoruba",                         'yo'),
                                  array(  "Chinese (Simplified)",           'zh'),
                                  array(  "Chinese (Traditional)",          'zh'),
                                  array(  "Zulu",                           'zu'));

?>